INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (1,'Make oil sure result','ES',5,'1989',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2,'Can issue tell whatever','FR',5,'1971',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (3,'Recent wrong thought music education trial','EN',4,'1989',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (4,'Develop leader who opportunity','EN',1,'2014',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (5,'Box there peace night','FR',1,'2006',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (6,'Raise goal especially sit himself','NL',3,'2013',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (7,'Here ten quickly itself option','EN',5,'1986',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (8,'Him different work','NL',6,'1981',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (9,'Game room true','ES',1,'1979',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (10,'Support simple society product Mr ball','EN',6,'1979',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (11,'Beat certain time many mouth foreign','NL',7,'2000',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (12,'Break party offer exactly whole','NL',6,'2009',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (13,'Example bed down','EN',6,'1973',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (14,'Politics surface easy among foreign','EN',5,'2010',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (15,'Practice wear find note interview','NL',6,'1972',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (16,'Decade perhaps gas machine say','FR',3,'1972',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (17,'Receive idea manage','EN',6,'1987',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (18,'Responsibility know crime agency class community','NL',2,'1988',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (19,'Several training choice','NL',5,'2019',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (20,'Radio which coach','ES',5,'1977',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (21,'Of school manager consider including cut','NL',6,'1980',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (22,'Speak action start attack food','ES',7,'1995',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (23,'Conference stand record deal challenge soldier','NL',3,'1987',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (24,'Necessary again however office away test','EN',7,'2001',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (25,'Him skin war','FR',6,'1989',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (26,'Shake lawyer environmental art ten','NL',2,'1987',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (27,'At accept relationship reason without difference','NL',5,'1975',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (28,'Family song add','ES',7,'2005',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (29,'Large call strategy price scene piece','EN',2,'1993',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (30,'Fine break benefit beautiful','ES',3,'1981',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (31,'Music but again','ES',6,'2004',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (32,'That pick close foot at I','FR',6,'1999',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (33,'Provide half strong others recently','EN',6,'2003',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (34,'Forward he sell','ES',3,'2008',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (35,'Less similar speak watch case onto','NL',1,'1978',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (36,'Southern about everything opportunity successful','NL',5,'2012',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (37,'Recent here public easy throw minute word','NL',6,'1990',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (38,'Camera maintain win if material maintain','FR',6,'2020',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (39,'Time former since whatever','NL',3,'1977',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (40,'Trip before area argue charge sign','EN',6,'1987',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (41,'Build foot operation expect tree','EN',2,'2020',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (42,'Unit wear value wait follow suddenly','ES',3,'2015',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (43,'Marriage talk drop become','NL',6,'1998',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (44,'Standard course language happen','EN',1,'1975',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (45,'Wonder media media writer','NL',3,'1980',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (46,'Box direction score question','ES',2,'2020',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (47,'Well list reach','FR',4,'2022',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (48,'Kitchen likely usually garden commercial','EN',1,'1973',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (49,'Either customer protect grow probably party','FR',5,'1987',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (50,'Teacher environment simply','FR',3,'1998',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (51,'Wife hair argue news','EN',1,'1999',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (52,'Couple foreign marriage yeah hand','EN',4,'1973',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (53,'Trade quickly reduce','ES',3,'2020',1);
