INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2000,'Protect decade foreign quickly challenge I','NL',1004,'1983',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2001,'Factor discover sing civil of book','EN',1004,'1991',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2002,'Protect without concern','EN',1007,'1999',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2003,'Choose employee pass yeah','FR',1003,'1979',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2004,'Production let protect','FR',1002,'2015',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2005,'A six southern hot','ES',1002,'1988',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2006,'Stuff yes particular including compare social','NL',1004,'1991',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2007,'Red forget improve first society laugh','ES',1001,'2020',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2008,'Process hundred oil camera','NL',1007,'2001',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2009,'Seven inside never street','NL',1004,'1996',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2010,'So trial later most','NL',1003,'1998',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2011,'Especially southern maybe to case','FR',1001,'2013',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2012,'Test model land','NL',1007,'1977',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2013,'Until trouble bag','ES',1006,'2012',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2014,'Material treatment star wear','NL',1001,'1971',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2015,'Forget organization pass receive model','FR',1005,'1993',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2016,'What international court join health','FR',1007,'2021',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2017,'Quickly save wait fear but serious','EN',1002,'1979',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2018,'Other however growth consider range value','ES',1002,'2020',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2019,'Situation enjoy significant many enter play','FR',1007,'2010',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2020,'Will material spend chance tax maybe','ES',1001,'1976',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2021,'Seven on college some','ES',1001,'1973',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2022,'Finish table yet','NL',1002,'2005',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2023,'Action discuss data north','ES',1001,'2002',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2024,'Page address several care represent','ES',1004,'1994',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2025,'Seem through fall himself','FR',1006,'1999',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2026,'Suffer myself book','ES',1003,'2002',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2027,'Yes throw less','FR',1001,'1996',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2028,'Unit community different knowledge','ES',1002,'1987',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2029,'That we really fish argue','NL',1006,'2010',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2030,'Actually trade book','EN',1002,'2022',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2031,'Production would office beautiful','ES',1006,'1983',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2032,'Rock price throughout scene professional board','EN',1007,'2010',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2033,'Occur control blue charge look','FR',1002,'2015',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2034,'Where poor spend company moment establish','NL',1006,'1999',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2035,'Wind occur explain decade quality','FR',1003,'1986',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2036,'Painting energy sense upon no nation another','NL',1007,'2013',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2037,'Star majority during certainly agree','FR',1002,'1975',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2038,'Upon land instead lay onto structure','NL',1001,'1990',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2039,'Leg such improve detail','NL',1002,'2007',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2040,'Democrat admit practice','NL',1005,'2006',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2041,'Bring inside practice','EN',1002,'2009',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2042,'Mean describe form would music huge','FR',1004,'1992',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2043,'Not each continue I not','NL',1002,'1976',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2044,'Sure bit watch find return we','ES',1007,'2009',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2045,'Clearly agree officer','NL',1002,'2022',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2046,'Health test old similar artist','EN',1003,'2015',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2047,'Growth left still teacher represent song','EN',1007,'1999',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2048,'Table maybe another','NL',1005,'1996',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2049,'Up move company where','EN',1002,'2009',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2050,'That more adult way box full','FR',1001,'1993',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2051,'Pattern safe analysis check turn board','FR',1004,'1981',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2052,'Dinner south town represent','NL',1004,'1974',1);
