INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (1,'Tree paper call or remain myself','NL',6,'1992',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (2,'Campaign travel together foot','NL',1,'1995',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (3,'Cup watch everybody local traditional','FR',6,'1989',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (4,'Place black choice conference','NL',5,'1977',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (5,'Also part poor','FR',1,'1996',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (6,'Reveal offer run','EN',3,'2005',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (7,'Letter soldier allow agent','FR',3,'2006',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (8,'College production stay','NL',4,'2020',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (9,'Individual by power PM son','NL',7,'2005',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (10,'Send gas sound tax stuff','NL',2,'2012',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (11,'Despite yourself good family which audience','ES',1,'2004',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (12,'Network eat start','ES',7,'1994',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (13,'Between partner side','FR',4,'2016',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (14,'Wish trouble protect heavy here','ES',6,'2017',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (15,'Hard story already form since letter','ES',5,'1977',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (16,'Government I hot vote','ES',2,'1994',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (17,'Throw place forget let','NL',7,'2020',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (18,'Later church step tonight prepare','EN',7,'1999',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (19,'Civil degree step career','FR',5,'1987',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (20,'Surface machine rest little','FR',1,'2017',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (21,'Popular benefit argue piece','NL',4,'2022',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (22,'Military moment lead their chance five','NL',7,'2020',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (23,'He present lawyer','EN',1,'2009',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (24,'Also while behavior large','EN',1,'1981',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (25,'Region before firm','EN',7,'2014',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (26,'Letter oil suggest include under','ES',6,'1983',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (27,'Full young young career','EN',5,'1973',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (28,'Foreign agent past','EN',2,'1984',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (29,'Both would street spend','FR',5,'1978',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (30,'Attention instead watch break lose air','EN',4,'2012',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (31,'Training hand check hundred analysis of','NL',5,'1999',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (32,'Can bill federal reflect sometimes','FR',3,'2009',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (33,'Far citizen author','NL',5,'2003',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (34,'Argue magazine generation whom','FR',7,'1986',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (35,'Deep huge at end throughout','ES',5,'1990',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (36,'Training own pressure ability everything whether','EN',5,'2001',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (37,'Television can probably affect direction upon','EN',5,'2009',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (38,'Nation street major decade design','EN',2,'1975',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (39,'Performance will free shoulder','FR',7,'2000',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (40,'Watch Democrat decision','NL',1,'1993',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (41,'Learn happy Mrs my','NL',1,'1983',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (42,'Foot model situation wear','NL',4,'1999',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (43,'Create feel third','EN',6,'1986',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (44,'Section up exactly development message','FR',1,'1980',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (45,'Movement only firm stock dream relate','EN',1,'1983',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (46,'Role prevent lead specific throughout my','FR',3,'1983',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (47,'From question television south a','EN',1,'2001',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (48,'Art discussion pressure business organization require','NL',4,'1988',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (49,'Along send piece year when','EN',2,'2020',0);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (50,'Conference only significant spend mother','FR',6,'1982',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (51,'President live sell','EN',7,'1977',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (52,'Term window allow meeting say','NL',7,'1982',1);
INSERT INTO book (book_id,book_title,book_language,book_author_id,book_year,book_read) VALUES (53,'Feel hear analysis method music','ES',6,'2018',0);
