version: 2
updates:
  - directory: /frontend
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      time: "04:00"
    ignore:
      # ignore typescript update due to Chakra ui error
      - dependency-name: "typescript"
