FROM node

WORKDIR /scripts

COPY package.json .

ARG NODE_ENV

RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
        else npm install --only=production; \
        fi

COPY . .

EXPOSE 3000

CMD ["npm", "start"]