version: '3'
services:
  backend:
    build:
      context: './backend'
      dockerfile: 'Dockerfile'
    stdin_open: true
    ports:
      - 8000:8000
    env_file:
      - ./env/backend.env
    depends_on:
      - database
    networks:
      - bookworm-net
  frontend:
    build:
      context: './frontend'
      dockerfile: 'Dockerfile'
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - backend
      - database
    networks:
      - bookworm-net
  database:
    image: 'postgres:13'
    ports:
      - 5432:5432
    env_file:
      - ./env/database.env
    networks:
      - bookworm-net
  test-runner:
    image: 'cypress'
    build: ./test
    container_name: cypress
    env_file:
      - ./env/test.env
    volumes:
      - ./test/cypress:/scripts/cypress
      - ./test/cypress.json:/scripts/cypress.json
    networks:
      - bookworm-net
networks:
  bookworm-net:
    driver: bridge
