version: "3"
services:
  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    container_name: bw_backend
    profiles: ["backend-only"]
    stdin_open: true
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - bookworm-net
  database:
    image: "postgres:13"
    container_name: bw_database
    profiles: ["backend-only"]
    ports:
      - 5432:5432
    networks:
      - bookworm-net
  test-runner:
    image: "cypress"
    build: ./e2e-tests
    container_name: bw_cypress
    profiles: ["test-only"]
    volumes:
      - ./e2e-tests/cypress:/scripts/cypress
      - ./e2e-tests/cypress.json:/scripts/cypress.json
    networks:
      - bookworm-net
  frontend:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    container_name: bw_frontend
    profiles: ["frontend-only"]
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - backend
      - database
    networks:
      - bookworm-net

networks:
  bookworm-net:
    driver: bridge
