version: '3'
services:
  backend:
    build:
      context: './backend'
      dockerfile: 'Dockerfile'
    container_name: bw_backend
    stdin_open: true
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - bookworm-net
  frontend:
    build:
      context: './frontend'
      dockerfile: 'Dockerfile'
    container_name: bw_frontend
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - backend
      - database
    networks:
      - bookworm-net
  database:
    image: 'postgres:13'
    container_name: bw_database
    ports:
      - 5432:5432
    networks:
      - bookworm-net
  test-runner:
    image: 'cypress'
    build: ./test
    container_name: bw_cypress
    profiles: ['test-only']
    volumes:
      - ./test/cypress:/scripts/cypress
      - ./test/cypress.json:/scripts/cypress.json
    networks:
      - bookworm-net
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    volumes:
      - ./themes/sometheme/:/opt/keycloak/themes/sometheme/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
    entrypoint: ['/opt/keycloak/bin/kc.sh', 'start-dev']
    ports:
      - 8080:8080
    networks:
      - bookworm-net

networks:
  bookworm-net:
    driver: bridge
