version: "3"
services:
  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    volumes:
      - "./backend:/scripts"
    stdin_open: true
    ports:
      - 8000:8000
    env_file:
      - ./env/backend.env
    depends_on:
      - database
    networks:
      - bookworm-net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  database:
    image: "postgres:13"
    ports:
      - 5432:5432
    env_file:
      - ./env/database.env

    networks:
      - bookworm-net
  frontend:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
      args:
        - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - "./frontend/src:/scripts/src"
    stdin_open: true
    tty: true
    env_file:
      - ./env/frontend.env
    depends_on:
      - backend
      - database
    networks:
      - bookworm-net
    command: npm run start
  test-runner:
    image: "cypress"
    build:
      context: "./e2e-tests"
      dockerfile: Dockerfile
    container_name: cypress
    env_file:
      - ./env/test.env
    volumes:
      - ./e2e-tests/cypress:/scripts/cypress
      - ./e2e-tests/cypress.json:/scripts/cypress.json
    networks:
      - bookworm-net
networks:
  bookworm-net:
    driver: bridge
