INSERT INTO author (author_id,author_name,author_books_written) VALUES (1000,'Alyssa Wise',16);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1001,'Kathy Barron',17);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1002,'Mario Ayers',19);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1003,'Luke Green',4);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1004,'Miss Emily Price PhD',6);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1005,'Dave Smith',3);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1006,'Paul Wood',2);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1007,'Amy Edwards',14);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1008,'Michael Collins',10);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1009,'Mary Pruitt',19);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1010,'James Hodges',20);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1011,'Diana Moore',7);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1012,'Mark Howard',14);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1013,'Richard Middleton',10);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1014,'Sue Vincent',11);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1015,'Shannon Ward',17);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1016,'Troy Gordon',14);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1017,'Mallory Peterson',15);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1018,'Maria Myers',13);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1019,'Donald Barber',13);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1020,'Carrie Lutz',8);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1021,'Laura Thompson',9);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1022,'Jason Wells',17);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1023,'Audrey Hall',11);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1024,'Stacy Murphy',0);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1025,'Brian Hensley',4);
INSERT INTO author (author_id,author_name,author_books_written) VALUES (1026,'Vickie Thompson MD',6);
