INSERT INTO book(book_title,book_language,book_author,book_year,book_read) VALUES ('I Am Charlotte Simons','EN','Tom Wolfe',2015,1);
INSERT INTO book(book_title,book_language,book_author,book_year,book_read) VALUES ('A God In Ruins','EN','Leon Uris',2015,1);
INSERT INTO book(book_title,book_language,book_author,book_year,book_read) VALUES ('Afrikaanse nachten','NL','Kiki Gallmann',2015,1);
INSERT INTO book(book_title,book_language,book_author,book_year,book_read) VALUES ('De mooiste verhalen uit de bijbel','NL','Kenneth Mc Leish',2015,1);
INSERT INTO book(book_title,book_language,book_author,book_year,book_read) VALUES ('Native Tongue','EN','Carl Hiaasen',2015,1);
INSERT INTO book(book_title,book_language,book_author,book_year,book_read) VALUES ('The Beach','EN','Alex Garland',2015,1);
INSERT INTO book(book_title,book_language,book_author,book_year,book_read) VALUES ('Ik, Zlatan','NL','Zlatan Ibrohamovic & David Lagerorantz',2016,1);
INSERT INTO book(book_title,book_language,book_author,book_year,book_read) VALUES ('Life of Pi','EN ','Yann Martel',2016,1);
INSERT INTO book(book_title,book_language,book_author,book_year,book_read) VALUES ('Mocro maffia','NL','Wouter Laumans & Marijn Schrijver',2016,1);
INSERT INTO book(book_title,book_language,book_author,book_year,book_read) VALUES ('The Heart Of Justice','EN ','William J. Coughlin',2016,1);
