import uuid

config = {
  "ADDRESS": [{"uuid": uuid.uuid4()} for i in range(300)],
  "AUTHOR": [{"uuid": uuid.uuid4()} for i in range(200)],
  "BOOK": [{"uuid": uuid.uuid4() } for i in range(500)],
  "BOOK_AUTHOR": [{"uuid": uuid.uuid4() } for i in range(500)],
  "BOOKWORM": [{"uuid": uuid.uuid4() } for i in range(599 - 2)],
  "CITY": [{"uuid": uuid.uuid4()} for i in range(200)],
  "COUNTRY": [{"uuid": uuid.uuid4()} for i in range(50)],
  "GENRE":[{"uuid": uuid.uuid4(), "genre": g} for g in [
    "Fantasy",
    "Science Fiction",
    "Dystopian",
    "Action & Adventure",
    "Mystery",
    "Horror",
    "Thriller & Suspense",
    "Historical Fiction",
    "Romance",
    "Women’s Fiction",
    "LGBTQ+",
    "Contemporary Fiction",
    "Literary Fiction",
    "Magical Realism",
    "Graphic Novel",
    "Short Story",
    "Young Adult",
    "New Adult",
    "Children’s",
    "Memoir & Autobiography",
    "Biography",
    "Food & Drink",
    "Art & Photography",
    "Self-help",
    "History",
    "Travel",
    "True Crime",
    "Humor",
    "Essays",
    "Guide / How-to",
    "Religion & Spirituality",
    "Humanities & Social Sciences",
    "Parenting & Families",
    "Science & Technology"
    ] 
  ],
  "INVENTORY": [{"uuid": uuid.uuid4()} for i in range(3100)],
  "LANGUAGE": [{"uuid": uuid.uuid4(), "language": l} for l in ["EN", "NL", "ES", "FR"]],
  "LIBRARY": [{"uuid": uuid.uuid4()} for i in range(2)],
  "PAGES_MAX":800,
  "PAGES_MIN":50,
  "PAYMENT":[{"uuid": uuid.uuid4()} for i in range(8000)],
  "RATING_MIN":1,
  "RATING_MAX":5,
  "RENTAL_RATE":[{"uuid": uuid.uuid4(), "rate": i + 0.99} for i in range(5)],
  "RENTAL":[{"uuid": uuid.uuid4()} for i in range(8000)],
  "REPLACEMENT_COST_MAX": 9,
  "REVIEW":[{"uuid": uuid.uuid4()} for i in range(180)],
  "STAFF":[{"uuid": uuid.uuid4()} for i in range(2)],
  "USER_ACCOUNT":[{"uuid": uuid.uuid4()} for i in range(599)],
  }